### ISSUE TITLE
The code for ImageNet10

### ISSUE THREAD

**Issue by TIEHua** [xpf/Data-Efficient-Backdoor-Attacks#2]
Thanks for sharing the source code. Do you have plan to open the code of ImageNet-10 experiment?

**Comment by xpf** [comment]
Sure, if needed. But I'm working on some other things right now, and it will probably take about a month or so. I promise to add the ImageNet-10 part after that.

**Comment by TIEHua** [comment]
> Sure, if needed. But I'm working on some other things right now, and it will probably take about a month or so. I promise to add the ImageNet-10 part after that.

Thank you very much.

**Comment by xpf** [comment]
> > Sure, if needed. But I'm working on some other things right now, and it will probably take about a month or so. I promise to add the ImageNet-10 part after that.
> 
> Thank you very much.

ImageNet-10 has been added.
